name: Update Winget

on:
  # release:  # disabled until current PR is merged
  #   types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.4.1)'
        required: true

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Submit to Winget
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: ys-ll.uniTerm
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }}
